### PR TITLE
Preserve relative indentation in auto indent

### LINKED ISSUE #40: Moving block including indents
If I have something like below and try to move lines 2-3 together, they will not maintain the indents -- 3 will be moved to the level of 2. The level difference should be maintained.

```
1
   2
      3
4
```

When I'm working with indented notes maintaining level differences is essential.

### PR DESCRIPTION
**Pull request by hugomg**
Fixes #40.

Instead of using == to reindent a block of code we now use < and > to
shift the block by the appropriate number of spaces. This way we
preserve the relative indentation between the lines, keeping the same
"shape".

### CODE REVIEW

**Comment by hugomg** [comment]
Part of me asks if it is worth replacing a single line of obviously working code with 20 lines of much more complicated logic. But I imagine it wouldn't hurt to create this PR.

**Comment by matze** [comment]
> Part of me asks if it is worth replacing a single line of obviously working code with 20 lines of much more complicated logic. 

Not a big deal in my opinion :-)

**Comment by hugomg** [comment]
Huh, I wonder why it wasn't able to figure it out by itself. Anyway, it should be mergeable now.

**Comment by matze** [comment]
:+1:

**Pull request merged**
